module.exports = [
  // charge
  'createCharge',
  'getCharges',
  'getCharge',
  'updateCharge',
  'deleteCharge',
  // driver
  'importDrivers',
  'exportDrivers',
  'getDrivers',
  'getDriver',
  'createDriver',
  'updateDriver',
  'deleteDriver',
  'uploadDriverImage',
  // good
  'createGood',
  'getGoods',
  'getGood',
  'updateGood',
  'deleteGood',
  // load
  'importLoads',
  'exportLoads',
  'exportLoad',
  'getLoads',
  'createLoad',
  'getLoad',
  'updateLoad',
  'deleteLoad',
  'payment',
  'paymentTransactions',
  // profile
  'importProfiles',
  'exportProfiles',
  'exportProfile',
  'getProfiles',
  'createProfile',
  'getProfile',
  'updateProfile',
  'deleteProfile',
  // users
  'isEmailsUnique',
  'importUsers',
  'exportUsers',
  'createUser',
  'getUsers',
  'getUser',
  'updateUser',
  'deleteUser',
  // countries
  'getAllCountries',
  'getAllStates',
  'getAllCities',
];
